export const Paths = {
  testIndex: '/test',
  pom: '/home',
  edit: '/edit',
  button: '/buttons',
  buttonAlt: '/button',
  dropdowns: '/dropdowns',
  alert: '/alert',
  frame: '/frame',
  frameUi: '/frameui',
  innerFrame: '/innerframe',
  radio: '/radio',
  window: '/window',
  elements: '/elements',
  draggable: '/draggable',
  droppable: '/droppable',
  sortable: '/sortable',
  selectable: '/selectable',
  slider: '/slider',
  waits: '/waits',
  table: '/table',
  advancedTable: '/advancedtable',
  calendar: '/calendar',
  forms: '/forms',
  file: '/file',
  shadow: '/shadow',
} as const;
